export const menuItemsData = [
    {
      id: 1,
      name: 'Mediterranean  Salad',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://tse1.mm.bing.net/th?id=OIP.TjUFWJYZHWWNYHpfr8lsawHaE7&pid=Api&P=0&w=257&h=171',
    },
    {
      id: 2,
      name: 'Summer Asian Slaw',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://tse4.mm.bing.net/th?id=OIP.412Q5qx2oqtjC3s_WavvdQHaE8&pid=Api&P=0&w=227&h=152',
    },
    {
      id: 3,
      name: 'Burger',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://tse2.mm.bing.net/th?id=OIP.kshlSfmumO5sH1WEDPKXoAHaJS&pid=Api&P=0&w=300&h=300',
    },
    {
      id: 4,
      name: 'white sauce pasta',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://tse3.mm.bing.net/th?id=OIP.nMvCZ5Gofd0YrGzXFFsw8AHaE8&pid=Api&P=0&w=226&h=152',
    },
    {
      id: 5,
      name: 'butterfly pasta',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://tse3.mm.bing.net/th?id=OIP.jXdRcmK-dlQhL5c6fcR1OQHaFj&pid=Api&P=0&w=209&h=157',
    },
    {
      id: 6,
      name: 'tooty fruity bowl',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://images.unsplash.com/photo-1616359523254-4b3b63fbb157?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NjR8fHRvb3R5JTIwZnJ1aXR5fGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      id: 7,
      name: 'granola cereal bowl',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://images.unsplash.com/photo-1500315331616-db4f707c24d1?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzF8fGdyYW5vbGElMjBjZXJlYWwlMjBib3dsfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      id: 8,
      name: 'palm bowl',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://tse2.mm.bing.net/th?id=OIP.6Ew3Sf32cA9l_5Lm9MSenAHaFj&pid=Api&P=0&w=204&h=154',
    },
    {
      id: 9,
      name: 'tigela smoothie',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://image.freepik.com/fotos-gratis/smoothie-de-tigela-de-acai-com-mirtilo-morango-chia_79295-1405.jpg',
    },
    {
      id: 10,
      name: 'breakfast cereal',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://images.unsplash.com/photo-1528711832838-46c60d34b4e3?ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8YnJlYWtmYXN0JTIwY2VyZWFsfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      id: 11,
      name: 'cuisine of hawaii',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://images.unsplash.com/photo-1625943553852-781c6dd46faa?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60',
    },
    {
      id: 12,
      name: 'fried chicken',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://images.unsplash.com/photo-1579670039509-e21e75007e4c?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzV8fGZyaWVkJTIwY2hpY2tlbnxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      id: 13,
      name: 'greek salad',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://images.unsplash.com/photo-1623855244697-5d8fbe9c7892?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fGdyZWVrJTIwc2FsYWR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      id: 14,
      name: 'hamburger',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://images.unsplash.com/photo-1552718752-c682d315b136?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTF8fGhhbWJ1cmdlcnxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      id: 15,
      name: 'israeli salad',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://images.unsplash.com/photo-1570197571499-166b36435e9f?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGlzcmFlbGklMjBzYWxhZHxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      id: 16,
      name: 'Pizza Pasta',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://images.unsplash.com/photo-1615192606904-9cee34bf93c4?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjJ8fHBpenphJTIwcGFzdGF8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      id: 17,
      name: 'Pizza',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: 'https://images.unsplash.com/photo-1594007654729-407eedc4be65?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8cGl6emF8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      id:18,
      name:'Rasgulla',
      info:'Rasgulla is a traditional Bengali sweet dessert recipe',
      price:24,
      img:'https://tse4.mm.bing.net/th?id=OIP.6KBVbhnQTyoIiLNbWqBQjAHaFX&pid=Api&P=0&w=213&h=155'
    },
    {
      id:19,
      name:'Rasmalai',
      info:' made with milk, an acidic ingredient, sugar and saffron.',
      price:40,
      img:'https://tse4.mm.bing.net/th?id=OIP.lgs2wlxBpGbm6Uub76eU4wHaHa&pid=Api&P=0&w=300&h=300'
    },
    {
      id:20,
      name:'Dilbahar',
      info:'Dilbahar',
      info:' traditional sweet, delicious combination of cashews,',
      price:50,
      img:"https://images.unsplash.com/photo-1578508053827-fe06d4dc2457?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDl8fGRpbCUyMGJhaGFyJTIwc3dlZXRzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60"

    }
  ];